blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/TheWayWithin/mcp-11/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://github.com/TheWayWithin/mcp-11/wiki
    about: Check our documentation for guides and tutorials
  - name: 🚀 Quick Start Guide
    url: https://github.com/TheWayWithin/mcp-11/blob/main/docs/QUICKSTART.md
    about: Get started with MCP-11 in 30 seconds